### ISSUE TITLE
Integrating Foreign Wrappers

### ISSUE THREAD

**Issue by DevGuyRash** [alexander-zuev/supabase-mcp-server#13]
When you add a foreign wrapper like the Stripe Integration on the Supabase site, and then you choose to add foreign tables, commands like `get_tables` will not be able those tables. They do appear in the Supabase SQL Editor when you query them directly. It's only in the MCP server that they do not appear.

---

![Image](https://github.com/user-attachments/assets/278eaccf-dbd7-4ed7-892e-dd4212d8d30e)

---

![Image](https://github.com/user-attachments/assets/f192372f-f06c-4cc8-9b23-8b63b88cc31a)

**Comment by alexander-zuev** [comment]
Oh, thanks for the report! I am not using foreign data wrappers so I wasn't checking this worked - will look into

**Comment by alexander-zuev** [comment]
Oh, thanks for the report! I am not using foreign data wrappers so I wasn't checking this worked - will look into

**Comment by alexander-zuev** [comment]
Thanks for raising again - I was excluding foreign tables in the `get_tables` tool previously. Can you please upgrade to v0.3.4 and confirm this is fixed @DevGuyRash ?

**Comment by DevGuyRash** [comment]
@alexander-zuev 

I don't believe it was fixed quite yet, but I appreciate the swift response!

Here are some screenshots of what's going on:

- Note: It DOES work with the `execute_sql_query` if I input a custom command to see the tables.

---

![Image](https://github.com/user-attachments/assets/91cdaa35-f08d-40ae-902b-9332b0d581ab)

---

Stripe tables showing is 0:

![Image](https://github.com/user-attachments/assets/167cc0a8-d707-464a-8ff6-2925d6941760)

---

![Image](https://github.com/user-attachments/assets/a526461d-b812-4fe3-b61e-fde0b38c4398)

**Comment by alexander-zuev** [comment]
Did you install v0.3.4 (just checking)? It should return or not exclude foreign tables? I'll create a couple on my side and test, OK

**Comment by DevGuyRash** [comment]
![Image](https://github.com/user-attachments/assets/5f859f7e-6ba3-4276-b4b6-32268848f982)

Yeah, I upgraded before doing anything. I can try restarting everything and seeing if it's just using the old until restart.

**Comment by DevGuyRash** [comment]
I restarted PC, uninstalled and re-installed, and it's still the same results as above. I do see the description for `get_tables` is the new one from v0.3.4:

![Image](https://github.com/user-attachments/assets/6efd71fb-f689-4d32-9393-d06a0de46842)

**Comment by alexander-zuev** [comment]
<img width="519" alt="Image" src="https://github.com/user-attachments/assets/4b5a6972-18ce-4e43-bd00-987000e59717" />

<img width="1205" alt="Image" src="https://github.com/user-attachments/assets/dadcbb6a-93ba-4ace-bbbc-889b21a62f1f" />

<img width="947" alt="Image" src="https://github.com/user-attachments/assets/0bb65f7c-a006-42d5-adde-69c4a0546474" />

Found what an issue with the way get_tables query was built - updated it to be a UNION of two queries:
- one for information_schema.tables
- another for information_schema.foreign_tables

Validated this works with a foreign table I've added.

Once the new version is released, I'll close this issue as it should be resolved.

Thanks for reporting @DevGuyRash !

**Comment by DevGuyRash** [comment]
Awesome, thank you! I think `get_db_schemas` was also affected, but I'm fine with `get_tables` working. Appreciate your hard work!

**Comment by alexander-zuev** [comment]
V0.3.5 released and fixed the schema query as well - thanks a lot @DevGuyRash !
